### PR TITLE
Only the ON_CLOSE and ON_MOVE events are required to call integrate

### LINKED ISSUE #176: [appimagelauncherd] don't try to integrate files while they're being copied into ~/Applications
Or this might happen:

```
Jun 24 01:21:29 xxxx appimagelauncherd[5686]: Something went wrong trying to read the squashfs image.
Jun 24 01:21:29 xxxx systemd[1804]: appimagelauncherd.service: Main process exited, code=killed, status=11/SEGV
Jun 24 01:21:29 xxxx systemd[1804]: appimagelauncherd.service: Failed with result 'signal'
```

An easy attempt would be to just compare file sizes between registration of a new file and integration attempt, and just re-queue the file in case that value changed. That's not too robust, though, if a file transfer for instance gets interrupted for instance, this method won't be able to detect that.

The question is what inotify detects when `scp` (the tool I used there) starts to receive data, and whether that event can be sorted out.

In any case, we must not terminate the application if the squashfs image can't be read.

### PR DESCRIPTION
**Pull request by azubieta**
The close event after a write operation is the one that give us a hint about a file download or copy operation finished. Therefore that's the only we should care about. The created or modified events only produce noise in this scenario.
 
fix #176

### CODE REVIEW

File: src/fswatcher/filesystemwatcher.cpp [hunk 1]
```diff
@@ -24,8 +24,7 @@ class INotifyEvent {
 class FileSystemWatcher::PrivateData {
 public:
     enum EVENT_TYPES {
-        fileCreationEvents = IN_CREATE | IN_MOVED_TO,
-        fileModificationEvents = IN_CLOSE_WRITE | IN_MODIFY,
+        fileCreationEvents = IN_CLOSE_WRITE | IN_MOVE,
```
Comment (TheAssassin) [inline src/fswatcher/filesystemwatcher.cpp]: What about `IN_CREATE`?

The name of the variable is imprecise now.

Comment (azubieta) [reply src/fswatcher/filesystemwatcher.cpp]: `IN_CREATE` tells about a file being created but it doesn't mean that the file has any content. Every time that an app create a file it must be open it in write mode in order to fill it. So monitoring the `IN_WRITE_CLOSE` is more precise.

Any suggestions for the variable name?

Comment (TheAssassin) [reply src/fswatcher/filesystemwatcher.cpp]: `fileChangeEvents` would do I guess.

Comment (azubieta) [reply src/fswatcher/filesystemwatcher.cpp]: done

**Comment by TheAssassin** [comment]
Just been editing the same file...
